added Zephyr links and update text
intive/patronage21-qa pull request #117
Opened 2021-06-15 09:34 UTC by Patrycja99

2021-06-15 11:39 UTC, kmiecikmarcin requested changes

2021-06-15 11:39 UTC, kmiecikmarcin commented on SeleniumProject/Features/REGISTRATION_FORMFormHandlingSteps.cs
> +﻿using System;
Stepsy do usunięcia. Nie generujemy pustych, bo potem nam lekki syf robią podczas automatyzacji.

2021-06-15 15:09 UTC, katkoch requested changes
Podłączę się pod review. Poki nie ma kodu, zostaw proszę '@ignore'.

2021-06-17 19:27 UTC, Iga221 approved these changes

2021-06-17 19:34 UTC, Iga221 approved these changes

2021-06-17 19:44 UTC, Iga221 approved these changes

2021-06-17 19:58 UTC, kmiecikmarcin approved these changes

2021-06-17 20:00 UTC, merged