IP2-185 scenarios for PUT method
intive/patronage21-qa pull request #14
Opened 2021-04-13 22:08 UTC by Marta9pa

2021-04-14 19:33 UTC, AdamAndrysek requested changes

2021-04-14 19:33 UTC, AdamAndrysek commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +And Updated user data can be checked
How exactly they can be checked? Where? It's not precise enough. Maybe it should sound like: 
"And the JSON body should contain" or something like this?

2021-04-14 19:33 UTC, AdamAndrysek commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +|<username> | <firstName> | <lastName> | <email> | <phoneNumber> | <gitHubUrl> | <code> | <message> |
I'm not 100% sure about this but:
let's assume the Scenario is starting with first row of data (line 26). So And will show you the message "firstName has been successfully changed" but username, firstName, lastName etc. will be the same as before the editing, because you're using the same set of data in the line 15 and 20. 

And one more thing: are you 100% sure that in Scenario Outline you can use tables with variables taken from another table? I'm just asking because that's new for me and my IDE doesn't show me line 25 in white and with italics, as it always does.

2021-04-14 19:33 UTC, AdamAndrysek commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +Then The server return status code <code>
As before: think about deleting one "code" from this sentence

2021-04-14 19:33 UTC, AdamAndrysek commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +When User send a request
sends

2021-04-14 19:33 UTC, AdamAndrysek commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +And JSON body in empty
is

2021-04-14 19:33 UTC, AdamAndrysek commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +|<username> | <firstName> | <lastName> | <email> | <phoneNumber> | <gitHubUrl> | <code> |
If the JSON body is empty, do you have to add Example?

2021-04-14 19:36 UTC, AdamAndrysek commented
Also please change the file name from SpecFlowFeature1.feature to something more definitive

2021-04-16 12:23 UTC, Marta9pa commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +|<username> | <firstName> | <lastName> | <email> | <phoneNumber> | <gitHubUrl> | <code> | <message> |
In lines 15 and 20 there are not the same data. 15 - input data, 20 - updated data. In the examples I put output data, after editing. Line 26 is the first example with updated data, and the second test will be run with data from this line. 
Do you think the first example should contains data from line 15?

2021-04-16 12:24 UTC, Marta9pa commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +|<username> | <firstName> | <lastName> | <email> | <phoneNumber> | <gitHubUrl> | <code> |
I think you're right. I deleted this.

2021-04-18 14:53 UTC, AdamAndrysek commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +|<username> | <firstName> | <lastName> | <email> | <phoneNumber> | <gitHubUrl> | <code> | <message> |
In my opinion the line 15 and 20 are the same variables which takes values from Example section. I know that you're thinking about input and uploaded data but when variables are named the same, I think here it's a problem. But we can wait for second review to be sure that I am right.

2021-04-20 01:48 UTC, js40598 requested changes

2021-04-20 01:48 UTC, js40598 commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +Description
It would be nice to have feature description. Even something simple like 

Using PUT method on URL /api/users
to edit User Data

2021-04-20 01:48 UTC, js40598 commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +|Tom34   | Wojciech | Nowak    | tom@gmail.com | 783984984   | htts://github.com/tom7u  | 200  | gitHubUrl is incorrect                  |
As @AdamAndrysek said, this may cause some problems. I propose to rename column titles by adding Before and After - 'usernameBefore', 'usernameAfter' to be sure everything is ok.

Examples looks like flow (user data after example is equal to user data in beginning of next example) but Background is ran for every example, so it creates user with initial data. Examples should work separately too.

You may want to write more examples like:
- check if every field can be successfully changed - it might be done in single example
- check validation of each field - validation rules should be provided by tech groups, if there is still problem with communication with Java team it would be good idea to check validation written by other groups, it will depend on each other anyway. There are validation rules provided by Android team https://tracker.intive.com/jira/browse/IP2-143, validation of user editing should be exactly the same as are for creation of user. Examples like providing too short or too long name would be nice.
- check editing user data to exactly the same as it was before


Example where other user than provided (userName is already used)  is needed should be created in separate scenario, to create additional step providing second user. You might also avoid this by just adding creation of second user into Background, but it will then be created for every single scenario, while it is needed for only one.

2021-04-20 01:48 UTC, js40598 commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +@mytag
Every '@mytag' can be removed or replaced by other tags.

2021-04-20 01:48 UTC, js40598 commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +Scenario Outline: 2_ Editing user who doesn’t exist in database
Scenarios can be renamed to

USER_EDIT_[/api/users]\_[PUT]\_\<number>\_IP2-89_\<title>

<number> and <title> to be replaced. Here it will look like 

USER_EDIT_[/api/users]_[PUT]_2_IP2-89_editing_user_who_does_not_exist_in_database

2021-04-20 01:48 UTC, js40598 commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +﻿Feature: Updating user data with PUT method
This file can be removed as it's new version is created.

2021-04-23 19:57 UTC, AdamAndrysek commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +Then The server returns status <code> and the message <message>
If all codes in Examples to this scenario are 200, maybe you should think about writing "The server returns status 200 and the message 'message'.

2021-04-23 19:57 UTC, AdamAndrysek commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +Then The server returns status <code> and the message <message>
The same situation about the code as it is in previous scenario, but here 400.

2021-05-03 21:07 UTC, hyurii commented on RestSharpProject/Features/SpecFlowFeature1.feature
> +|Tom34| Tomasz | Nowak | tom@gmail.com | 783984984 | https://github.com/tom7u |
i belive u can press ctrl+f to format it

2021-05-03 21:12 UTC, hyurii approved these changes

2021-05-03 21:12 UTC, hyurii commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +| usernameBefore | firstNameBefore | lastNameBefore | emailBefore   | phoneNumberBefore | gitHubUrlBefore          |
I dont like this postfix Before and Request. It affect readability

2021-05-03 21:12 UTC, hyurii commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +Then The server returns status <code> and the message <message>
I disagree. This is one beautiful generic step. Do not see the reason to have two one with 400 and one with 200 and in the future more.

2021-05-03 21:12 UTC, hyurii commented on RestSharpProject/Features/IP2-185-API-editing-user-data.feature
> +Then The server returns status <code> and the message <message>
the same as above

2021-05-04 09:41 UTC, AdamAndrysek approved these changes

2021-05-04 11:54 UTC, js40598 approved these changes

2021-05-04 12:05 UTC, merged