feature/IP2-270-BDD-GWT-users-screen
intive/patronage21-qa pull request #15
Opened 2021-04-14 01:11 UTC by js40598

https://tracker.intive.com/jira/browse/IP2-270

2021-04-18 09:31 UTC, WysockiPatryk requested changes
Request for a few minor changes

2021-04-18 09:31 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/UsersScreen.feature
> +Scenario: USERS_SCREEN__IP2-152_users_screen_displayed_correctly
Could you add the numbers of scenarios?
You might even have two underscores between the feature name and the ticket

2021-04-18 09:31 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	Then User see "<name>" in "<list>" list
The 's' is missing for verbs

2021-04-18 09:31 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/UsersScreen.feature
> +| Anna Nowak   | Liderzy    |
Since we are searching for users that must be available, we'll have to add them before this test and then remove them. Maybe it's worth giving them unique names that are unlikely to appear in real life?

2021-04-18 09:31 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	Given No existing user named "not existing user"
'Given' is a bit incomprehensible at first glance, maybe something like that:
_There is no user named "not existing user"_ or
_User "not existing user" does not exist_

2021-04-18 09:31 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	And Second existing user "Anna Nowak" assigned to "Liderzy" list and "Group 3" group
'Given' + 'And' should be unified for easier implementation
_(without 'Second' and add table with sample data)_

2021-04-18 09:31 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	And No other user is named "Jan Kowalski"
Without unique test names this can be problematic

2021-04-18 21:11 UTC, js40598 commented on patronage21-qa-appium/Features/UsersScreen.feature
> +Scenario: USERS_SCREEN__IP2-152_users_screen_displayed_correctly
I will add them later, to avoid numbering them all over again with every removal of scenario. Double underscore is to mark place where those numbers will be added.

2021-04-18 21:11 UTC, js40598 commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	Then User see "<name>" in "<list>" list
Done

2021-04-18 21:11 UTC, js40598 commented on patronage21-qa-appium/Features/UsersScreen.feature
> +| Anna Nowak   | Liderzy    |
Names will be modified later on. We don't know yet if we will have to create them before testing. We also can have set of users prepared for testing or even use API to manage them. Having them prepared earlier is good as it does not require to create them every time tests are run. They will remain the same after execution of scenarios, so they could stay as long as we are still in production of app. For testing purposes Android team might also hardcode users to avoid connecting with database this early, so we would be able to test app with UI only, and later, when API will be connected we might have to test only connecting with database. Anyway, we don't know yet how it will work, we will see.

2021-04-18 21:11 UTC, js40598 commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	Given No existing user named "not existing user"
Done

2021-04-18 21:11 UTC, js40598 commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	And Second existing user "Anna Nowak" assigned to "Liderzy" list and "Group 3" group
Done

2021-04-18 21:12 UTC, js40598 commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	And No other user is named "Jan Kowalski"
Names will be modified later on.

2021-04-18 21:41 UTC, WysockiPatryk approved these changes
Approved

2021-04-24 09:41 UTC, kmiecikmarcin approved these changes

2021-04-24 09:41 UTC, kmiecikmarcin commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	Given User is on "Users" screen
Instead Background do this in Hooks?

2021-04-24 09:44 UTC, kmiecikmarcin approved these changes

2021-04-24 09:44 UTC, kmiecikmarcin commented on patronage21-qa-appium/Features/UsersScreen.feature
> +https://tracker.intive.com/jira/browse/IP2-152
#Task in QA Team: 
#Task in Android Team:

2021-04-24 10:24 UTC, js40598 commented on patronage21-qa-appium/Features/UsersScreen.feature
> +	Given User is on "Users" screen
In my opinion it's nice to keep it inside Gherkin like now to be sure what's going on in tests without checking code.

2021-04-24 10:24 UTC, js40598 commented on patronage21-qa-appium/Features/UsersScreen.feature
> +https://tracker.intive.com/jira/browse/IP2-152
Done

2021-04-24 10:30 UTC, kmiecikmarcin approved these changes

2021-04-24 10:35 UTC, WysockiPatryk approved these changes

2021-04-24 10:52 UTC, merged