Feature/ip2 171 code home page
intive/patronage21-qa pull request #17
Opened 2021-04-15 19:04 UTC by paulina-dzinowagis

2021-04-15 22:42 UTC, js40598 requested changes

2021-04-15 22:42 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Given I am on Home page
We voted to write third person scenarios.

2021-04-15 22:42 UTC, js40598 commented on patronage21-qa-appium/Steps/AppiumAndSpecFlowWorksSteps.cs
> -﻿using System;
This file and it's Feature file can be deleted. It was created to check if Appium and SpecFlow works after creating project. Now, when app tests appears, they confirm it anyway, otherwise they would not run.

2021-04-15 22:42 UTC, js40598 commented on patronage21-qa-appium/Steps/BaseSteps.cs
> +        }
TearUp should be named TearDown if it works after scenario.

2021-04-16 09:52 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Given I am on Home page
Ok, right

2021-04-16 09:52 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Steps/AppiumAndSpecFlowWorksSteps.cs
> -﻿using System;
I would like to leave this test because it is the only test that is passed currently and we can show it during Demo.  This file was generated automatically but I spent so much time implementing the code.

2021-04-16 09:52 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Steps/BaseSteps.cs
> +        }
Ok

2021-04-23 13:29 UTC, js40598 requested changes

2021-04-23 13:29 UTC, js40598 commented on patronage21-qa-appium/Steps/HomeNavigationSteps.cs
> +                button.Click();
You could use Dictionary here to avoid changing Feature file this much, like

var buttons = new Dictionary<string, string>()
{
    { "Audyt zdarzeń", "Miniaturka modułu audytu zdarzeń"},
    { "Grupy technologiczne", "Miniaturka modułu grup technologicznych"},
    etc.
};
var button = _driver.FindElementByAccessibilityId(buttons[buttonId])

2021-04-23 13:29 UTC, js40598 commented on patronage21-qa-appium/Steps/HomeNavigationSteps.cs
> +        }
To fix that app is being run too many times every scenario we could set Background status by navigating through app. There are three states where those scenarios might end - turned off app, on Home screen or one level deeper than Home (one Back click away). We could check if we are on Home screen already and if we are, we don't need to re-run app. If we are not on Home screen, there are two possible ways - we are one level deeper or we left app (navigation to one of screens failed and Back button was pressed). We can ignore dividing it and just re-run app if we aren't on Home screen or split it into two (re-run app if it's closed or press Back if it's on one of 'second level' screens like Calendar or Users)

2021-04-23 13:29 UTC, js40598 commented on patronage21-qa-appium/Steps/BaseSteps.cs
> +        }
We might need a feature specific TearDown in future. For now, it would be nice to totally remove it to save time while testing. In comment about Background I've explained more.

2021-04-23 13:29 UTC, js40598 commented on patronage21-qa-appium/Steps/AppiumAndSpecFlowWorksSteps.cs
> +            Thread.Sleep(1000);
If you still want to keep this file for some reason,
Thread.Sleep(1000); 
can be removed, Appium waits for app to start anyway.

2021-04-25 17:12 UTC, katkoch approved these changes

2021-04-27 16:41 UTC, katkoch submitted a review, later dismissed

2021-04-27 17:58 UTC, katkoch submitted a review, later dismissed

2021-04-29 11:14 UTC, katkoch approved these changes

2021-04-29 17:44 UTC, js40598 approved these changes
Approve

2021-04-29 18:42 UTC, merged