BDD-GWT-IP2-91 added user download and user editing feature
intive/patronage21-qa pull request #19
Opened 2021-04-16 10:51 UTC by Iga221

2021-04-16 14:52 UTC, WysockiPatryk requested changes

2021-04-16 14:52 UTC, WysockiPatryk commented on SeleniumProject/Features/UserEditing.feature
> +Then The user description is saved
Missing data saving _(e.g. User clicks 'Save' button)_.
Or does the data save itself in the background? I cannot find a description for this page/feature

2021-04-16 14:52 UTC, WysockiPatryk commented on SeleniumProject/Features/UserEditing.feature
> +﻿Feature: UserEditing
Have you thought about using tables with sample data?

2021-04-16 14:52 UTC, WysockiPatryk commented on SeleniumProject/Features/UserEditing.feature
> +Given User changes the project
'Given' and 'When' in these scenarios are not clear for me.
They look like the same step.

2021-04-16 14:52 UTC, WysockiPatryk commented on SeleniumProject/Features/UserEditing.feature
> +Then An error appears
What kind of error? Maybe you could add text message here?

2021-04-16 14:52 UTC, WysockiPatryk commented on SeleniumProject/Features/UserDownload.feature
> +Scenario: 1_User is looking for a specific user correctly
When user try to find someone:
'correctly' -> 'successfully'
'incorrectly' -> 'unsuccessfully'

2021-04-16 14:52 UTC, WysockiPatryk commented on SeleniumProject/Features/UserDownload.feature
> +Given User is on the <users> page
You can add it as 'Background'

2021-04-19 21:55 UTC, WysockiPatryk requested changes

2021-04-19 21:55 UTC, WysockiPatryk commented on SeleniumProject/Features/UserDownload.feature
> +And User selects <wszystkie grupy technologiczne> and clicks <enter> button
Move the second 'and' to the new line as the next step
_"User clicks <enter> button"_ is repeated often, it will be more convenient to automate

2021-04-20 18:07 UTC, AdamAndrysek requested changes

2021-04-20 18:07 UTC, AdamAndrysek commented on SeleniumProject/Features/UserDownload.feature
> +Scenario: 1_User is looking for a specific user successfully
You have to rewrite every Scenario title because of new ways of writing them.

2021-04-20 18:07 UTC, AdamAndrysek commented on SeleniumProject/Features/UserDownload.feature
> +Scenario: 6_User is looking for a specific user without providing all data
I think that scenario titles should be unique so you shouldn't use the same title twice, as it is on 5 and 6. These titles should be also more precise. This is also about Scenario 7

2021-04-20 18:07 UTC, AdamAndrysek commented on SeleniumProject/Features/UserEditing.feature
> +Given User changes email adress
I'm not sure about "Given" in scenarios from 1 to 8. Maybe it's possible to get rid of "Given" – check if it's allowed to do so.

2021-04-23 13:19 UTC, WysockiPatryk requested changes
![IP2-91](https://user-images.githubusercontent.com/24721195/115876918-2d9f9b00-a447-11eb-9cfd-405774b51e4f.png)
Few small things

2021-04-27 20:47 UTC, WysockiPatryk requested changes

2021-04-27 20:47 UTC, WysockiPatryk commented on SeleniumProject/Features/UserDownload.feature
> -Given User is on the <users> page
Why did you removed Background?

2021-04-27 20:47 UTC, WysockiPatryk commented on SeleniumProject/Features/UserDownload.feature
> +And  User selects '<technology group>'
Missing underscore _(technology_group)_
Check it also in other scenarios

2021-04-27 20:47 UTC, WysockiPatryk commented on SeleniumProject/Features/UserDownload.feature
> +Scenatio Outline: USERS_PAGE_1_IP2-91_User_is_looking_for_a_specific_user_successfuly
Scenatio -> Scenario

2021-04-27 20:47 UTC, WysockiPatryk commented on SeleniumProject/Features/UserEditing.feature
>  And User writes more or less than 9 numbers
Here you can also add table and rewrite step to something like
_User writes an incorrect phone number '&lt;phone_number&gt;'_
| phone_number |
| 12345678          |
| 1234567890      |

2021-04-28 09:20 UTC, kmiecikmarcin commented on SeleniumProject/Features/UserDownload.feature
> -Given User is on the <users> page
You can do this in Hooks.

2021-04-29 04:14 UTC, WysockiPatryk commented on SeleniumProject/Features/UserDownload.feature
> +Given User '<user_data>' exists
[https://docs.specflow.org/projects/specflow/en/latest/Gherkin/Gherkin-Reference.html](https://docs.specflow.org/projects/specflow/en/latest/Gherkin/Gherkin-Reference.html)
`Placing single quotation marks (') around placeholders (eg. '&lt;placeholder&gt;')improves SpecFlow’s ability to parse the scenario outline and generate more accurate regular expressions and test method signatures.`

2021-04-29 08:09 UTC, kmiecikmarcin commented on SeleniumProject/Features/UserDownload.feature
> +Given User '<user_data>' exists
But it doesn't work. I tried it and gherkin generated steps for only first example.  Maybe I did something wrong? but what

2021-04-29 20:05 UTC, Marta9pa commented on SeleniumProject/Features/UserDownload.feature
> +When User enters the '<user_data>' he wants to find in the "szukaj użytkownika" field
I think you can just wirte "User enters the <user_data> in the "szukaj użytkownika" field." You don't need to write that "he wants to find", because it follows from the title of the scenario.

2021-04-29 20:54 UTC, Marta9pa commented on SeleniumProject/Features/UserDownload.feature
>  When User writes the user's name and surname in the <szukaj użytkownika> field
the user's name and surname -> '<user_data>'
<szukaj użytkownika> -> "szukaj użytkownika"

2021-04-29 20:54 UTC, Marta9pa commented on SeleniumProject/Features/UserEditing.feature
You didn't mention about the button "zatwierdź" for saving changes (scenarios 1-8).

2021-04-29 20:54 UTC, Marta9pa commented on SeleniumProject/Features/UserDownload.feature
> +When User enters the '<user_data>' he wants to find in the "szukaj użytkownika" field
I think you can just wirte "User enters the <user_data> in the "szukaj użytkownika" field." You don't need to write that "he wants to find", because it follows from the title of the scenario.

2021-05-06 15:41 UTC, katkoch approved these changes

2021-05-07 09:49 UTC, WysockiPatryk approved these changes

2021-05-07 13:35 UTC, merged