feature/BDD-GWT-IP2-181-Verification-of-activation-code
intive/patronage21-qa pull request #20
Opened 2021-04-18 18:59 UTC by katkoch

scenarios for verification of activation code

2021-04-20 18:17 UTC, AdamAndrysek requested changes

2021-04-20 18:17 UTC, AdamAndrysek commented on RestSharpProject/Features/VerificationOfActivationCode.feature
> +	Given User is in data base
database. It should be corrected also in next scenarios.

2021-04-20 18:17 UTC, AdamAndrysek commented on RestSharpProject/Features/VerificationOfActivationCode.feature
> +	And is not activated
Maybe better it'd be: 
And his status is INACTIVE

2021-04-20 18:17 UTC, AdamAndrysek commented on RestSharpProject/Features/VerificationOfActivationCode.feature
> +	And User is activated
Maybe: JSON body contains "status": "ACTIVE"
What do you think?

2021-04-20 18:17 UTC, AdamAndrysek commented on RestSharpProject/Features/VerificationOfActivationCode.feature
> +	Then Verification is succesfull,
Should be "successful", not "succesfull". Please change it also in next scenarios.

2021-04-23 19:59 UTC, AdamAndrysek approved these changes

2021-04-23 21:04 UTC, kmiecikmarcin approved these changes

2021-04-24 09:11 UTC, merged