IP2-273-BDD-GWT-events-audit-screen
intive/patronage21-qa pull request #22
Opened 2021-04-20 14:17 UTC by WysockiPatryk

Feature: Events Audit screen
	User should be able to see the list of app's events and people associated with them
	Task in Android board: https://tracker.intive.com/jira/browse/IP2-158
	Task in QA board: https://tracker.intive.com/jira/browse/IP2-273

2021-04-22 13:48 UTC, js40598 requested changes

2021-04-22 13:48 UTC, js40598 commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	| Aktualizacja danych |
Those events have to exist first, for now we are sure that there is at least one registered user (account we are logged into while testing this, of course if login feature will be implemented before we test this), but we are not sure if any user ever changed his data, logged out or even logged in (first log in may appear as register, I'm not sure, but 'login', 'data update', 'data addition' and 'errors' are called examples, so there might be some other types of events)

Besides that, not really important, table edge is not straight.

2021-04-22 13:48 UTC, js40598 commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	| zxc123    |
Opposite to  previous comment, we need to ensure that user does not exist, but here it depends on database, if it will be blank at beginning of feature then providing unique username like now should be enough.

2021-04-22 13:48 UTC, js40598 commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	| Nowak     |
It would be nice to ensure that user exists. For example
Given User "<user_name>" exists in database

2021-04-22 13:48 UTC, js40598 commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	| Od najnowszych  |
We need to ensure that there are multiple events in database.

2021-04-23 12:24 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	| Nowak     |
Updated

2021-04-23 12:24 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	| zxc123    |
Updated

2021-04-23 12:24 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	| Aktualizacja danych |
Events list will be updated when it will be implemented on the backend side.
Event does not have to exist before the test is performed. This scenario tests primarily filtering.
The issue of steps-code implementation.

2021-04-23 12:25 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	| Od najnowszych  |
Issue of steps-code implementation _(will be updated in future)_

2021-04-23 13:58 UTC, paulina-dzinowagis requested changes

2021-04-23 13:58 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	Then Header "Audyt zdarzeń" is visible
I propose to use a scenario outline here:
`Then User sees "<element_name>" element`

2021-04-23 13:58 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +Scenario: EVENTS_AUDIT_1_IP2-158_Events_audit_displays_correctly
I propose to change to EVENTS_AUDIT_1_IP2-158_Events_audit_page_displayed_correctly

2021-04-23 13:58 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	Given User "<user_name>" exists in database
`exists` shall be in the quotes to achieve generic step

2021-04-23 13:58 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	Given User "<user_name>" does not exist in database
`does not exist` shall be in the quotes to achieve generic step

2021-04-23 13:58 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	Given User is on "Events audit" screen
I propose to change `screen` to `page` to be unified with the same steps from HomeNavigation.feature

2021-04-23 14:09 UTC, paulina-dzinowagis requested changes

2021-04-23 14:09 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	When User searches for '<event>' in events list
In my opinion, we shall ensure here that at least one event of each type was performed before.
Additionally, we can prepare here negative cases for events that never had been performed.

2021-04-23 15:10 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	Given User "<user_name>" exists in database
Already corrected

2021-04-23 15:10 UTC, WysockiPatryk commented on patronage21-qa-appium/Features/EventsAuditScreen.feature
> +	Given User "<user_name>" does not exist in database
Already corrected

2021-05-29 15:18 UTC, closed without merging