Feature/bdd code ip2 184 form module
intive/patronage21-qa pull request #24
Opened 2021-04-22 15:24 UTC by kmiecikmarcin

2021-04-23 09:07 UTC, hyurii requested changes

2021-04-23 09:07 UTC, hyurii commented on RestSharpProject/Steps/FormModuleSteps.cs
> +            var takeErrorFromResponse = parseRestResponse["fields"]["email"][0].ToString();
you should use User model here

2021-04-23 09:07 UTC, hyurii commented on RestSharpProject/Steps/FormModuleSteps.cs
> +            ScenarioContext.Current.Add("user", user);
are you really need to use ScenarioContext? simple field is not enough for user and response?

2021-04-29 11:01 UTC, katkoch approved these changes

2021-05-03 16:26 UTC, js40598 approved these changes

2021-05-03 21:30 UTC, hyurii approved these changes
you should not put generated files into repo. ex * feature.cs

2021-05-03 21:30 UTC, hyurii commented on RestSharpProject/Steps/RegistrationFormSteps.cs
> +        string email = User.GenerateEmailAdress();
this should be part of domain model as one method CreateUser()

2021-05-03 21:30 UTC, hyurii commented on RestSharpProject/Steps/RegistrationFormSteps.cs
> +            technologies.Add("QA");
Enum fits here better in my opinion

2021-05-03 21:30 UTC, hyurii commented on RestSharpProject/Features/RegistrationForm.feature
> +#https://tracker.intive.com/jira/browse/IP2-314
Im struggling that we dont have step to check if post rly register user. for example Get , but maybe in the future we can update it

2021-05-04 07:24 UTC, merged