Feature/BDD-CODE-IP2-243-registration-form
intive/patronage21-qa pull request #30
Opened 2021-05-03 15:35 UTC by kmiecikmarcin

2021-05-03 18:06 UTC, katkoch requested changes

2021-05-03 18:06 UTC, katkoch commented on SeleniumProject/Steps/RegistrationFormSteps.cs
> +            Assert.That(errorAboutEmailAdress.Text, Is.EqualTo("Niepoprawny adres e-mail"));
I am not sure if this assertion is ok. In your  'Then'  you are looking for element that has text "niepoprawny adres e-mail" and in assertion you are checking, if text which you found is "niepoprawny adres e-mail". You found it by XPath in the first place, so you can't be wrong. I think you should check if the element exists.
It goes to all your assertions.

2021-05-08 18:48 UTC, kmiecikmarcin commented on SeleniumProject/Pages/RegistrationFormPage.cs
> +        {
W tej funkcji jest logika, której nie powinno być w Page Object. Będzie do refaktoryzacji.

2021-05-09 13:52 UTC, katkoch requested changes

2021-05-09 15:34 UTC, katkoch approved these changes
Previously written minor mistakes can be fixed later.

2021-05-09 18:12 UTC, Marta9pa approved these changes

2021-05-13 13:40 UTC, katkoch submitted a review, later dismissed

2021-05-17 17:54 UTC, Marta9pa submitted a review, later dismissed

2021-05-18 12:11 UTC, closed without merging