add new scenarios to Form Handlins Steps 1
intive/patronage21-qa pull request #39
Opened 2021-05-16 11:50 UTC by Patrycja99

2021-05-17 08:27 UTC, kmiecikmarcin requested changes

2021-05-17 08:27 UTC, kmiecikmarcin commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +When The user clicks button 'Execiute'
W każdym kroku zamiast 'Execiute' -> 'execute'

2021-05-17 08:27 UTC, kmiecikmarcin commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +And send the enquiry to API
And send the enquiry to API  -> And send the request to API

2021-05-17 08:27 UTC, kmiecikmarcin commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +Scenario: REGISTRATION_FORM_STEP_1_IP2_293_Verification_side_is_not_visible
Ten scenariusz z tym następnym chyba nawet powinny być jako jeden. Strona związana z errorem wyświetli nam się plus da nam wiadomość.

2021-05-17 17:40 UTC, kmiecikmarcin commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +And send the enquiry to API
A tak dodatkowo to jest to Selenium to nie wiem, czy jest to dobre by był tu związany krok z API i restsharpem.

2021-05-19 08:43 UTC, kmiecikmarcin approved these changes

2021-05-19 16:22 UTC, Iga221 approved these changes

2021-05-19 18:04 UTC, Patrycja99 commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +Scenario: REGISTRATION_FORM_STEP_1_IP2_293_Verification_side_is_not_visible
Jeden negatywny ma być jak user źle wypełni formularz, wtedy nie może przejść dalej.
Drugi negatywny jak np system się wywali.

2021-05-19 18:06 UTC, Patrycja99 commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +When The user clicks button 'Execiute'
Teraz jest ' Załóż konto' tak jak powinno być

2021-05-20 08:33 UTC, kmiecikmarcin requested changes

2021-05-20 08:33 UTC, kmiecikmarcin commented on SeleniumProject/Features/IP2_293FormHandlingSteps.cs
> +using TechTalk.SpecFlow;
Ten plik powinien być w SeleniumProject/Steps/ nie w Feature

2021-05-20 18:43 UTC, katkoch commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +Scenario: REGISTRATION_FORM_STEP_1_IP2_293_Verification_side_is_visible
zmien prosze "side" na "site",

2021-05-20 18:43 UTC, katkoch commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +And should get e-mail with werification code
zmien proszę "werification" na verification

2021-05-20 18:43 UTC, katkoch commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +Then Response is successful
Odpowiedz jest sukcesem jesli user bedzie przeniesiony na nastepna strone. wg mnie "response is successful" nie jest niezbedna.

2021-05-20 18:43 UTC, katkoch commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +And should get e-mail with werification code
Czy Twoje testy będą także weryfikować czy user dostanie mail z kodem?

2021-05-21 14:51 UTC, Patrycja99 commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +And should get e-mail with werification code
OMG co za rażący błąd

2021-05-21 14:52 UTC, Patrycja99 commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +And should get e-mail with werification code
nie

2021-05-21 19:58 UTC, Iga221 commented on SeleniumProject/Features/IP2-293FormHandling.feature
> +When The user clicks button 'załóz konto'
załóż

2021-05-22 10:37 UTC, kmiecikmarcin approved these changes

2021-05-22 10:41 UTC, Iga221 approved these changes

2021-05-24 19:39 UTC, kmiecikmarcin approved these changes

2021-05-24 19:47 UTC, merged