IP2-11 Selenium and Specflow Project
intive/patronage21-qa pull request #4
Opened 2021-03-27 22:55 UTC by Marta9pa

Selenium project with specflow has been created using the solution from the branch master.

2021-03-28 22:38 UTC, paulina-dzinowagis requested changes
The project should be placed directly under _Solution_, not in the _Solution Items_ folder.

2021-03-28 22:38 UTC, paulina-dzinowagis commented on SeleniumProject/SeleniumProject.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
Here should be the _net5.0_ framework.

2021-03-30 13:59 UTC, Marta9pa commented on SeleniumProject/SeleniumProject.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
Could you please check it once again? It should be ok now.

2021-04-01 17:16 UTC, paulina-dzinowagis approved these changes

2021-04-01 18:56 UTC, merged