feature/BDD_CODE_IP2_591-List_of-technology-groups
intive/patronage21-qa pull request #44
Opened 2021-05-18 21:05 UTC by Marta9pa

2021-05-19 22:54 UTC, js40598 requested changes

2021-05-19 22:54 UTC, js40598 commented on RestSharpProject/Steps/ListOfTechnologyGroupsSteps.cs
> +            Assert.That(responseMessage.groups[4], Is.EqualTo("Pearl Advanced"));
Would be nice to ensure that test will work even if order of tech groups will change. Like that

            Assert.That(responseMessage.groups.Contains("Java"), Is.True);
            Assert.That(responseMessage.groups.Contains("JavaScript"), Is.True);
            Assert.That(responseMessage.groups.Contains("QA"), Is.True);
            Assert.That(responseMessage.groups.Contains("Mobile (Android)"), Is.True);

You could also check if amount of groups is correct 

            Assert.That(responseMessage.groups.Count, Is.EqualTo(4));

"Pearl Advanced" group has been removed from api.

2021-05-19 22:54 UTC, js40598 commented on RestSharpProject/Steps/ListOfTechnologyGroupsSteps.cs
> +            client = new RestClient("http://intive-patronage.pl:9101");
Url has been changed to
http://intive-patronage.pl

2021-05-23 22:09 UTC, Marta9pa commented on RestSharpProject/Steps/ListOfTechnologyGroupsSteps.cs
> +            Assert.That(responseMessage.groups[4], Is.EqualTo("Pearl Advanced"));
That's a good solution, I changed asserts, thanks.

2021-05-23 22:10 UTC, Marta9pa commented on RestSharpProject/Steps/ListOfTechnologyGroupsSteps.cs
> +            client = new RestClient("http://intive-patronage.pl:9101");
Changed.

2021-05-23 23:04 UTC, js40598 approved these changes

2021-05-24 20:24 UTC, merged