IP2-99-form-module
intive/patronage21-qa pull request #7
Opened 2021-04-06 13:43 UTC by kmiecikmarcin

2021-04-06 19:32 UTC, katkoch reviewed
I checked your scenarios and made some suggestions.

2021-04-06 19:32 UTC, katkoch commented on RestSharpProject/Features/FormModule.feature
> +	#Task in QA Team: https://tracker.intive.com/jira/browse/IP2-99
This is the issue from JS board, not QA board.

2021-04-06 19:32 UTC, katkoch commented on RestSharpProject/Features/FormModule.feature
> +Scenario: 2 Send request filling data and checking all fields
"checking all fields" - which fields do you mean? Technological groups or "zgoda obowiazkowa" and regulamin?

2021-04-06 19:32 UTC, katkoch commented on RestSharpProject/Features/FormModule.feature
> +	Then The server should return error message about
The end of this sentence is unfinished.

2021-04-06 19:32 UTC, katkoch commented on RestSharpProject/Features/FormModule.feature
> +	When I send request to API marked all technology groups fields
Could you rephrase this sentence?

2021-04-06 19:32 UTC, katkoch commented on RestSharpProject/Features/FormModule.feature
> +	Then The server should execution request and return empty body
The server should **execute** request and return the empty body.

2021-04-06 19:32 UTC, katkoch commented on RestSharpProject/Features/FormModule.feature
> +
Maybe one more scenario about "hasło", which will be different from "powtórz hasło"?

2021-04-06 19:32 UTC, katkoch commented on RestSharpProject/Features/FormModule.feature
> +Scenario: 10 Send request marking two fields from 'Technologie'
Maybe a scenario with 3 marked technologies would be better? (edge case)

2021-04-06 19:37 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +Scenario: 2 Send request filling data and checking all fields
All this fields

2021-04-07 19:43 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +	#Task in QA Team: https://tracker.intive.com/jira/browse/IP2-99
Done

2021-04-07 19:43 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +Scenario: 2 Send request filling data and checking all fields
Done

2021-04-07 19:44 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +	Then The server should return error message about
Done

2021-04-07 19:44 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +	When I send request to API marked all technology groups fields
Done

2021-04-07 19:44 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +	Then The server should execution request and return empty body
Done

2021-04-07 19:44 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +
Done

2021-04-07 19:44 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +Scenario: 10 Send request marking two fields from 'Technologie'
Done

2021-04-07 21:13 UTC, AdamAndrysek requested changes
My review - some cosmetic changes and suggestions

2021-04-07 21:13 UTC, AdamAndrysek commented on RestSharpProject/Features/FormModule.feature
>  	Given I fill required data
Please observe the Gherkin poll results - if the QA group decides to write Gherkin scenarios in 3rd person, unfortunately you should change it everywhere in your Feature file.

2021-04-07 21:13 UTC, AdamAndrysek commented on RestSharpProject/Features/FormModule.feature
>  	When I send request to API without fields: 'Hasło' and 'Powtórz hasło'
I'm not sure if the "without fields: 'Hasło' and 'Powtórz hasło'" is necessary here - from Given we know that you don't fill these fields.
If you think you can omit this extract of a sentence, you should also make changes to similar steps in scenarios below and above this one.

2021-04-07 21:13 UTC, AdamAndrysek commented on RestSharpProject/Features/FormModule.feature
>  	Then The server should return error message about missing data
What do you think about the Scenario when user encounters a server error? 
And what do you think about adding response codes to Then?

2021-04-08 08:55 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +	Then The server should return error message about marked to much technology groups
Done

2021-04-08 08:56 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
> +Scenario: 7 Form module Send request without marked fields: 'JavaScript, Java, QA, Mobile'
Done

2021-04-08 08:56 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
>  	Then The server return empty body
Done

2021-04-08 08:57 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
>  	Then The server should return error message about missing field 'Imię'
I did this into like this: "Then The server should return status 200 with empty JSON body". What do you think?

2021-04-08 08:57 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
>  	Given I fill required data
Done

2021-04-08 08:57 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
>  	When I send request to API without fields: 'Hasło' and 'Powtórz hasło'
I changed this.

2021-04-08 09:00 UTC, kmiecikmarcin commented on RestSharpProject/Features/FormModule.feature
>  	Then The server should return error message about missing data
I added status code. I am not sure about scenarios with server error. I could check only situation when status code in respsonse will not equal to 500.

2021-04-08 19:41 UTC, katkoch approved these changes
The lines are a little long, but I guess it would be hard to make them shorter.
Please correct "Then - line" in Scenario 2.

2021-04-09 13:56 UTC, AdamAndrysek approved these changes

2021-04-11 09:34 UTC, merged