BDD_GWT_IP2-676_Adding_projects
intive/patronage21-qa pull request #79
Opened 2021-06-03 16:54 UTC by Marta9pa

2021-06-04 17:32 UTC, js40598 requested changes

2021-06-04 17:32 UTC, js40598 commented on RestSharpProject/Features/AddingProjects.feature
> +Scenario outline: PROJECT_LIMIT_1_[api/users]_[PUT]_IP2-676_Adding_project_to_user_account
Scenario outline -> Scenario Outline

2021-06-04 17:32 UTC, js40598 commented on RestSharpProject/Features/AddingProjects.feature
> +Scenario outline: PROJECT_LIMIT_2_[api/users]_[PUT]_IP2-676_Adding_more_than_five_different_projects_to_user_account
Scenario outline -> Scenario Outline

2021-06-04 23:25 UTC, Marta9pa commented on RestSharpProject/Features/AddingProjects.feature
> +Scenario outline: PROJECT_LIMIT_1_[api/users]_[PUT]_IP2-676_Adding_project_to_user_account
poprawione

2021-06-04 23:25 UTC, Marta9pa commented on RestSharpProject/Features/AddingProjects.feature
> +Scenario outline: PROJECT_LIMIT_2_[api/users]_[PUT]_IP2-676_Adding_more_than_five_different_projects_to_user_account
poprawione

2021-06-05 00:04 UTC, js40598 submitted a review, later dismissed

2021-06-05 18:44 UTC, js40598 approved these changes

2021-06-05 18:49 UTC, merged