Feature/IP2-170-BDD home page
intive/patronage21-qa pull request #8
Opened 2021-04-06 15:25 UTC by js40598

Home Page test scenarios written in Gherkin

2021-04-06 18:20 UTC, WysockiPatryk requested changes
Jeden pusty krok
Reszta wygląda dobrze

2021-04-06 18:40 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	And No action was taken
Gherkin służy raczej do opisu, który nie powinien zostawiać żadnych wątpliwości niezależnie kto go czyta, a samo "The app is running" mogłoby być dość mylne, w końcu byłoby prawdziwe na każdym ekranie. Za to gdyby zmienić to na  'I am on "Home" page', to odpadałby test ze sprawdzeniem czy faktycznie jesteśmy na Home. Żeby go przywrócić musielibyśmy wyrzucić cały Background, ale wtedy znowu musimy powtarzać w większości testów 'I am on "Home" page'. Nie znalazłem lepszego rozwiązania, które dokładnie opisywałoby stan w którym ma być aplikacja i pozwalało nie powtarzać kroków. Lepiej w kodzie zostawić jeden pusty krok, niż nie mieć pewności co się dzieje w scenariuszach.

2021-04-06 18:55 UTC, kmiecikmarcin commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	And No action was taken
Background: 
 	Given I am on "Home" page

Scenario:1_HOME_PAGE_IP2-93_Home Page is a first screen seen
	Then User should see  'Home' page navigation

@js40598 co sądzisz?

Chodzi o to, że w momencie gdy znajdujesz się na ekranie startowym, nie sprawdzasz czy faktycznie tam "jesteś", tylko czy ten ekran wraz z nawigacją istnieje.

2021-04-06 19:15 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	And No action was taken
@kmiecikmarcin jest w porządku, w jakimś stopniu łączy moją i Patryka wersję, poprawiam.

2021-04-06 19:30 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	And No action was taken
@kmiecikmarcin mam na myśli Twój komentarz przed edycją, ten po edycji już mi nie pasuje bo ogólnie wszystkie te testy sprawdzają właśnie czy Home działa, jak wszystkie przejdą to znaczy, że tak, nie ma sensu na to pisać dodatkowego testu.

2021-04-06 21:04 UTC, hyurii reviewed
Nice, try to add one more complex scenario. use navigation to several places, use back button.

2021-04-06 21:23 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +Scenario:1_HOME_PAGE_IP2-93_Home Page displayed correctly
Just for this one scenario as it is more static or for every single scenario? If for every, won't it make scenarios less readable?

2021-04-06 21:27 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +Scenario:1_HOME_PAGE_IP2-93_Home Page displayed correctly
I mean snail case notation for 'home_page_displayed_correctly' might be less readable than 'Home Page displayed correctly'. Anyway, I may be wrong.

2021-04-07 13:10 UTC, hyurii commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +Scenario:1_HOME_PAGE_IP2-93_Home Page displayed correctly
module should be first to group scenarios later in CI. 
u decide about snail notation. 'Home Page displayed correctly' - looks for me weird , first words are uppercase, u use dash in the begining of title scenario.

2021-04-08 19:53 UTC, paulina-dzinowagis requested changes

2021-04-08 19:53 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Then I am on "Tech groups" page
Scenarios from 2 to 7 could be more generic in my opinion. We could use one scenario outline for them like in the example here https://www.baeldung.com/cucumber-scenario-outline.

2021-04-08 19:53 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Then I am on "Home
Here we could use a scenario outline too.

2021-04-09 17:54 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Then I am on "Home
I'm not sure how to use a scenario outline here, wouldn't it have to look like that?
![obraz](https://user-images.githubusercontent.com/56318458/114220891-d8568a80-996c-11eb-98ec-739636c6e88f.png)
Or maybe I'm doing it wrong.

2021-04-09 18:04 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Then I am on "Tech groups" page
Done

2021-04-11 19:10 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Then I am on "Home
It's my suggestion:

```
Scenario:HOME_PAGE_3_IP2-93_back_to_home_page_navigation`
	When I click on <button_name> button
	And I click on Back button
	Then I am on Home page

Examples: 
    | button_name |
    | Grupy technologiczne |
    | Użytkownicy |
    | Dzienniczek |
    | Kalendarz |
    | Audyt zdarzeń |
```

2021-04-11 19:13 UTC, paulina-dzinowagis requested changes

2021-04-11 19:13 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +# zephyr link
I propose to create all Zephyr links or create a new task for it in the backlog and remove all occurrences from the code.

2021-04-11 19:13 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +#Scenario:HOME_PAGE__IP2-93_home_page_breadcrumbs_navigation_to_home_page
The same as for Zephyr links.

2021-04-11 19:24 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Then I am on "Home
I was asked by hyurii to do it in one complex scenario, anyway if you see this wrong I will correct this.

2021-04-11 19:33 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +	Then I am on "Home
Done

2021-04-11 19:37 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +# zephyr link
We established that we create Zephyr links together with merging branch, there is no point in creating them now, while scenarios are being changed.

2021-04-11 19:37 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +#Scenario:HOME_PAGE__IP2-93_home_page_breadcrumbs_navigation_to_home_page
We established that we create Zephyr links together with merging branch, there is no point in creating them now, while scenarios are being changed.

2021-04-11 20:32 UTC, paulina-dzinowagis commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +#Scenario:HOME_PAGE__IP2-93_home_page_breadcrumbs_navigation_to_home_page
I mean scenario for breadcrumbs.

2021-04-11 23:09 UTC, js40598 commented on patronage21-qa-appium/Features/HomeNavigation.feature
> +#Scenario:HOME_PAGE__IP2-93_home_page_breadcrumbs_navigation_to_home_page
Ok, done

2021-04-12 09:05 UTC, paulina-dzinowagis approved these changes

2021-04-12 09:23 UTC, WysockiPatryk approved these changes

2021-04-12 22:31 UTC, merged